"""
Django settings for soilcore project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# -------------------------
# Base Directory
# -------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------
# Security & Debug
# -------------------------
SECRET_KEY = 'django-insecure-284n^dwcj7we)ny7ucj&@=qnz#olyw*g8e+e)(__!g_h46^fu!'
DEBUG = True  # Set to False in production

ALLOWED_HOSTS = []
# Example for deployment:
#

ALLOWED_HOSTS = ["soil-monitoring.onrender.com", "localhost", "127.0.0.1"]
CSRF_TRUSTED_ORIGINS = ["https://soil-monitoring.onrender.com",
    "http://localhost",
    "http://127.0.0.1"
]

# -------------------------
# Timezone / Localization
# -------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'  # Local timezone
USE_I18N = True
USE_TZ = True

# -------------------------
# Installed Apps
# -------------------------
INSTALLED_APPS = [
    # Django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'account',
    'soilcore',
    'weather',
    'soildata',
    'chatApp',  
    'soilvision',
]

# -------------------------
# Middleware
# -------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Whitenoise for static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',  
]

# -------------------------
# Static files (CSS, JS, Images)
# -------------------------
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------
# Static files (CSS, JS, images)
# ---------------------------

STATIC_URL = '/static/'

# Development: where your static files are stored
STATICFILES_DIRS = [BASE_DIR / "static"]

# Production: where collectstatic will put all files
STATIC_ROOT = BASE_DIR / "staticfiles"   # <-- REQUIRED for collectstatic

# Optional: WhiteNoise for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ---------------------------
# Media files (uploads)
# ---------------------------

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------
# URL Configuration
# -------------------------
ROOT_URLCONF = 'soilcore.urls'

# -------------------------
# Templates
# -------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Project-wide templates
        'APP_DIRS': True,  # Templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.global_profile',
            ],
        },
    },
]

# -------------------------
# WSGI
# -------------------------
WSGI_APPLICATION = 'soilcore.wsgi.application'

# -------------------------
# Database (SQLite by default)
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------
# Password validation
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -------------------------
# Default primary key field type
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------
# Login URLs (used by @login_required)
# -------------------------
LOGIN_URL = '/accounts/login/'  
LOGIN_REDIRECT_URL = '/soildata/dashboard/'  


#=======================================        API SECTION       ==================================
# -------------------------
# Weather API Settings
# -------------------------

OPENWEATHER_API_KEY = "963804a07802e5371e2a2bd19f6a7afb"
WEATHER_CACHE_SECONDS = 900  

#-----------------------
# Unsplash API
#------------------------

UNSPLASH_ACCESS_KEY = '1p8c8r_JXHlH5-CStbJgX5JNheF7_7YanrgSftDbZX8'

# -------------------------
# Google Custom Search API Settings
# -------------------------

SEARCH_ENGINE_ID = "d4f67ec45810c4c76"

# -------------------------
# Chat / OpenAI / Gemini
# -------------------------
GEMINI_API_KEY = "AIzaSyApn9GD0Db1H7tGX4KbqpL2_9DeqOUPZco"
CHAT_HISTORY_LIMIT = 500


#=========================----------------------========================-------------------==================
# -------------------------
# Email (example)
# -------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'soilmonitor2025@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('iekb dktq cfcl gnxc')  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# -------------------------
# Channels (for chat app)
# -------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# -------------------------
# Optional MySQL config (commented)
# -------------------------
"""
import os
from dotenv import load_dotenv
load_dotenv()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'railway'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    }
}
"""


