# Generated by Django 5.2.6 on 2026-01-16 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'db_table': 'soilcore_newsletter',
            },
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('moisture_min', models.FloatField()),
                ('moisture_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('humidity_min', models.FloatField()),
                ('humidity_max', models.FloatField()),
                ('salinity_min', models.FloatField()),
                ('salinity_max', models.FloatField()),
                ('crops', models.TextField(help_text='Comma-separated crop names suitable for this soil')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Soil Type',
                'verbose_name_plural': 'Soil Types',
                'db_table': 'soilcore_soiltype',
            },
        ),
        migrations.CreateModel(
            name='SoilPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_crops', models.TextField(help_text='Comma-separated predicted crops')),
                ('ph', models.FloatField()),
                ('moisture', models.FloatField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('salinity', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='soil_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilcore_predictions', to=settings.AUTH_USER_MODEL)),
                ('soil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='soilcore.soiltype')),
            ],
            options={
                'verbose_name': 'Soil Prediction',
                'verbose_name_plural': 'Soil Predictions',
                'db_table': 'soilcore_soilprediction',
                'ordering': ['-created_at'],
            },
        ),
    ]
